[package]
name = "reciptmanagement"
version = "0.1.0"
authors = ["doenis <d.st@this.com>"]

[dependencies]
postgres = "0.15.1"
serde_json = "1.0.4"
serde = "1.0.16"
serde_derive = "1.0.16"
rocket = "0.3.3"
rocket_codegen = "0.3.3"
rocket_contrib = "0.3.3"